In [1]:
import pandas as pd

## Jumlah Record dan Jumlah Attribute

In [14]:
df = pd.read_csv("international_matches.csv")
df

,date,home_team,away_team,home_team_continent,away_team_continent,home_team_fifa_rank,away_team_fifa_rank,home_team_total_fifa_points,away_team_total_fifa_points,home_team_score,...,shoot_out,home_team_result,home_team_goalkeeper_score,away_team_goalkeeper_score,home_team_mean_defense_score,home_team_mean_offense_score,home_team_mean_midfield_score,away_team_mean_defense_score,away_team_mean_offense_score,away_team_mean_midfield_score
0,1993-08-08,Bolivia,Uruguay,South America,South America,59,22,0,0,3,...,No,Win,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1993-08-08,Brazil,Mexico,South America,North America,8,14,0,0,1,...,No,Draw,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1993-08-08,Ecuador,Venezuela,South America,South America,35,94,0,0,5,...,No,Win,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1993-08-08,Guinea,Sierra Leone,Africa,Africa,65,86,0,0,1,...,No,Win,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1993-08-08,Paraguay,Argentina,South America,South America,67,5,0,0,1,...,No,Lose,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23916,2022-06-14,Moldova,Andorra,Europe,Europe,180,153,932,1040,2,...,No,Win,65.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23917,2022-06-14,Liechtenstein,Latvia,Europe,Europe,192,135,895,1105,0,...,No,Lose,NaN,65.0,NaN,NaN,NaN,NaN,NaN,NaN
23918,2022-06-14,Chile,Ghana,South America,Africa,28,60,1526,1387,0,...,Yes,Lose,79.0,74.0,75.5,76.7,78.2,75.5,76.0,78.2
23919,2022-06-14,Japan,Tunisia,Asia,Africa,23,35,1553,1499,0,...,No,Lose,73.0,NaN,75.2,75.0,77.5,70.8,72.3,74.0
23920,2022-06-14,Korea Republic,Egypt,Asia,Africa,29,32,1519,1500,4,...,No,Win,75.0,NaN,73.0,80.0,73.8,NaN,79.3,70.8

## Nama Attribute,Jumlah attribute objek dan Jumlah attribute angka

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23921 entries, 0 to 23920
Data columns (total 25 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   date                           23921 non-null  object
 1   home_team                      23921 non-null  object
 2   away_team                      23921 non-null  object
 3   home_team_continent            23921 non-null  object
 4   away_team_continent            23921 non-null  object
 5   home_team_fifa_rank            23921 non-null  int64
 6   away_team_fifa_rank            23921 non-null  int64
 7   home_team_total_fifa_points    23921 non-null  int64
 8   away_team_total_fifa_points    23921 non-null  int64
 9   home_team_score                23921 non-null  int64
 10  away_team_score                23921 non-null  int64
 11  tournament                     23921 non-null  object
 12  city                           23921 non-null  object
 13  country                        23921 non-null  object
 14  neutral_location               23921 non-null  bool
 15  shoot_out                      23921 non-null  object
 16  home_team_result               23921 non-null  object
 17  home_team_goalkeeper_score     8379 non-null   float64
 18  away_team_goalkeeper_score     8095 non-null   float64
 19  home_team_mean_defense_score   7787 non-null   float64
 20  home_team_mean_offense_score   8510 non-null   float64
 21  home_team_mean_midfield_score  8162 non-null   float64
 22  away_team_mean_defense_score   7564 non-null   float64
 23  away_team_mean_offense_score   8312 non-null   float64
 24  away_team_mean_midfield_score  7979 non-null   float64
dtypes: bool(1), float64(8), int64(6), object(10)
memory usage: 4.4+ MB

In [15]:
df.shape

(23921, 25)

## Rata-rata home_team_fifa_rank

In [4]:
df ["home_team_fifa_rank"].mean()

77.85468834914928

## Nilai minimal home_team_fifa_rank

In [5]:
df ["home_team_fifa_rank"].min()

1

## Nilai Maksimum home_team_fifa_rank

In [6]:
df ["home_team_fifa_rank"].max()

211

## Jumlah attribute yang memiliki nilai null

In [7]:
df.isna().any().sum()

8

## Tampilan isi dari dictionary

In [11]:
home_team_fifa_rank = ["70","59","8","35","52"]
city = ["La Paz","Solna","Buenos Aires","Sydney","Seoul"]
df = pd.DataFrame({
    "home_team_fifa_rank":home_team_fifa_rank,
    "city":city
})

In [12]:
df.head()

  home_team_fifa_rank          city
0                  70        La Paz
1                  59         Solna
2                   8  Buenos Aires
3                  35        Sydney
4                  52         Seoul

## Menampilkan nilai minimum,maksimum,standar devisiasi,Q1,Q2,dan Q3

In [16]:
df.describe()

,home_team_fifa_rank,away_team_fifa_rank,home_team_total_fifa_points,away_team_total_fifa_points,home_team_score,away_team_score,home_team_goalkeeper_score,away_team_goalkeeper_score,home_team_mean_defense_score,home_team_mean_offense_score,home_team_mean_midfield_score,away_team_mean_defense_score,away_team_mean_offense_score,away_team_mean_midfield_score
count,23921.000000,23921.000000,23921.000000,23921.000000,23921.000000,23921.000000,8379.000000,8095.000000,7787.000000,8510.000000,8162.000000,7564.000000,8312.000000,7979.000000
mean,77.854688,80.797375,323.401488,315.453576,1.609214,1.068266,74.963838,74.212477,74.903249,75.818743,75.889292,74.424379,75.420019,75.259143
std,52.355225,53.232902,500.825725,490.944273,1.630127,1.263944,8.212242,8.225919,6.003114,6.268416,6.053110,5.937425,6.201906,6.124573
min,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,47.000000,47.000000,52.800000,53.300000,54.200000,52.800000,53.300000,54.200000
25%,33.000000,36.000000,0.000000,0.000000,0.000000,0.000000,70.000000,69.000000,71.000000,71.700000,72.500000,70.500000,71.300000,71.800000
50%,71.000000,73.000000,0.000000,0.000000,1.000000,1.000000,75.000000,74.000000,75.200000,75.700000,76.200000,74.500000,75.300000,75.500000
75%,115.000000,119.000000,547.000000,523.000000,2.000000,2.000000,81.000000,80.000000,78.800000,80.000000,79.500000,78.200000,79.700000,79.000000
max,211.000000,211.000000,2164.000000,2164.000000,31.000000,21.000000,97.000000,97.000000,91.800000,93.000000,93.200000,91.800000,93.000000,93.200000

## Menampilkan nilai korelasi attribute bertipe angka

In [17]:
df.corr()

C:\Users\USER\AppData\Local\Temp\ipykernel_18272\1134722465.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr()

,home_team_fifa_rank,away_team_fifa_rank,home_team_total_fifa_points,away_team_total_fifa_points,home_team_score,away_team_score,neutral_location,home_team_goalkeeper_score,away_team_goalkeeper_score,home_team_mean_defense_score,home_team_mean_offense_score,home_team_mean_midfield_score,away_team_mean_defense_score,away_team_mean_offense_score,away_team_mean_midfield_score
home_team_fifa_rank,1.000000,0.496644,-0.177332,-0.061516,-0.127667,0.219087,0.026064,-0.640102,-0.210219,-0.712681,-0.706093,-0.736180,-0.197999,-0.219993,-0.219073
away_team_fifa_rank,0.496644,1.000000,-0.045389,-0.158492,0.298982,-0.158206,0.034015,-0.248486,-0.626912,-0.241540,-0.254718,-0.256242,-0.698827,-0.703529,-0.730467
home_team_total_fifa_points,-0.177332,-0.045389,1.000000,0.923608,0.018280,-0.045954,0.014227,0.202064,0.110484,0.200774,0.160734,0.213823,0.070885,-0.003438,0.072898
away_team_total_fifa_points,-0.061516,-0.158492,0.923608,1.000000,-0.073670,0.044622,0.010146,0.109012,0.214212,0.095147,0.057744,0.103302,0.181379,0.107349,0.189590
home_team_score,-0.127667,0.298982,0.018280,-0.073670,1.000000,-0.171268,-0.051037,0.110092,-0.156870,0.135689,0.139203,0.142802,-0.159974,-0.142025,-0.149705
away_team_score,0.219087,-0.158206,-0.045954,0.044622,-0.171268,1.000000,0.093234,-0.082294,0.165525,-0.082411,-0.088926,-0.084401,0.161526,0.171400,0.178541
neutral_location,0.026064,0.034015,0.014227,0.010146,-0.051037,0.093234,1.000000,-0.016036,-0.038887,0.020085,0.040003,-0.000917,-0.019329,-0.007676,-0.019221
home_team_goalkeeper_score,-0.640102,-0.248486,0.202064,0.109012,0.110092,-0.082294,-0.016036,1.000000,0.183310,0.709909,0.606479,0.675313,0.170853,0.162261,0.175306
away_team_goalkeeper_score,-0.210219,-0.626912,0.110484,0.214212,-0.156870,0.165525,-0.038887,0.183310,1.000000,0.163079,0.153481,0.151401,0.693181,0.586533,0.662816
home_team_mean_defense_score,-0.712681,-0.241540,0.200774,0.095147,0.135689,-0.082411,0.020085,0.709909,0.163079,1.000000,0.807094,0.843612,0.171837,0.170735,0.185069
home_team_mean_offense_score,-0.706093,-0.254718,0.160734,0.057744,0.139203,-0.088926,0.040003,0.606479,0.153481,0.807094,1.000000,0.770460,0.170301,0.170051,0.178025
home_team_mean_midfield_score,-0.736180,-0.256242,0.213823,0.103302,0.142802,-0.084401,-0.000917,0.675313,0.151401,0.843612,0.770460,1.000000,0.171367,0.164153,0.172823
away_team_mean_defense_score,-0.197999,-0.698827,0.070885,0.181379,-0.159974,0.161526,-0.019329,0.170853,0.693181,0.171837,0.170301,0.171367,1.000000,0.787763,0.829846
away_team_mean_offense_score,-0.219993,-0.703529,-0.003438,0.107349,-0.142025,0.171400,-0.007676,0.162261,0.586533,0.170735,0.170051,0.164153,0.787763,1.000000,0.757958
away_team_mean_midfield_score,-0.219073,-0.730467,0.072898,0.189590,-0.149705,0.178541,-0.019221,0.175306,0.662816,0.185069,0.178025,0.172823,0.829846,0.757958,1.000000

## Merubah tipe data integer menjadi float dengan tiga angka belakang koma

In [22]:
df["home_team_fifa_rank"]*0.001

0        0.059
1        0.008
2        0.035
3        0.065
4        0.067
         ...
23916    0.180
23917    0.192
23918    0.028
23919    0.023
23920    0.029
Name: home_team_fifa_rank, Length: 23921, dtype: float64

    ## Menampilkan 10 record pertama dari attribute bertipe angka

In [24]:
Angka=df.select_dtypes(include=["int64"]).head(10)
Angka

,home_team_fifa_rank,away_team_fifa_rank,home_team_total_fifa_points,away_team_total_fifa_points,home_team_score,away_team_score
0,59,22,0,0,3,1
1,8,14,0,0,1,1
2,35,94,0,0,5,0
3,65,86,0,0,1,0
4,67,5,0,0,1,3
5,70,19,0,0,0,1
6,50,102,0,0,2,0
7,65,86,0,0,4,0
8,111,9,0,0,0,7
9,4,3,0,0,1,2

In [26]:
Angka.to_csv("Posttest_2.csv", index=False)